services:
  web:
    container_name: catbot_0.5.1a
    build: .
    restart: always
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --noinput
      && uvicorn config.asgi:application --host 0.0.0.0 --port 8000"
    volumes:
      - ./static:/app/static
      - ./data:/app/data
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/app/static:ro
      # Ниже пути к вашим сертификатам
      - /etc/letsencrypt/live/riopass.ddns.net/fullchain.pem:/etc/letsencrypt/live/riopass.ddns.net/fullchain.pem
      - /etc/letsencrypt/live/riopass.ddns.net/privkey.pem:/etc/letsencrypt/live/riopass.ddns.net/privkey.pem
    depends_on:
      - web

volumes:
  static: